services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: "postgresql+psycopg://user:password@db:5432/omni_player"
    ports:
      - "3000:8000"
    restart: unless-stopped